site_name: AutoAGI Documentation
site_url: https://docs.agpt.co/
repo_url: https://github.com/KhulnaSoft/AutoAGI
repo_name: AutoAGI
edit_uri: edit/master/docs/content
docs_dir: content
nav:
  - Home: index.md

  - The AutoAGI Platform 🆕: 
    - Getting Started: 
        - Setup AutoAGI (Local-Host): platform/getting-started.md
        - Edit an Agent: platform/edit-agent.md
        - Delete an Agent: platform/delete-agent.md
        - Download & Import and Agent: platform/download-agent-from-marketplace-local.md 
        - Create a Basic Agent: platform/create-basic-agent.md
        - Submit an Agent to the Marketplace: platform/submit-agent-to-marketplace.md   
    - Advanced Setup: platform/advanced_setup.md
    - Agent Blocks: platform/agent-blocks.md
    - Build your own Blocks: platform/new_blocks.md
    - Using Ollama: platform/ollama.md
    - Using D-ID: platform/d_id.md
    - Blocks: platform/blocks/blocks.md
    - Contributing:
        - Tests: platform/contributing/tests.md
  - Contribute: contribute/index.md
  - License: https://github.com/KhulnaSoft/AutoAGI/blob/master/LICENSE

theme:
  name: material
  custom_dir: overrides
  language: en
  icon:
    repo: fontawesome/brands/github
    logo: material/book-open-variant
    edit: material/pencil
    view: material/eye
  favicon: assets/favicon.png
  features:
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    # - navigation.path
    - toc.follow
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: ['.','../']
      check_paths: true
      dedent_subsections: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - table-reader
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KhulnaSoft/AutoAGI
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/khulnasoft
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/autoagi/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/autoagi
      
extra:
  analytics:
    provider: google
    property: G-XKPNKB9XG6

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - _javascript/tablesort.js
  - _javascript/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
